### ISSUE TITLE
[Bug]: Annoying "Deployment operation progress" stuck/duplicate in console

### ISSUE THREAD

**Issue by OfficialEsco** [Trenly/winget-pkgs#156] opened 2022-02-18 15:35 UTC
### Brief description of your issue

See Actual behavior

### Steps to reproduce

Find a Manifest with a few MSIX packages, or do a loop in `Mozilla.Firefox.Nightly`

### Expected behavior

A much cleaner view and to not be visible on the PR submitting screen

### Actual behavior

Much worse than this
```
Deployment operation progress: C:\Users\Esco\AppData\Local\… [Completed🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨 ]
Deployment operation progress: Mozilla.MozillaFirefoxNightly… [Completed🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨 ]
Deployment operation progress: C:\Users\Esco\AppData\Local\… [Completed🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨 ]
Deployment operation progress: Mozilla.MozillaFirefoxNightly… [Completed🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨 ]
Deployment operation progress: C:\Users\Esco\AppData\Local\… [Completed


🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨
🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨Deployment operation progress: Mozilla.MozillaFirefoxNightly… [Completed
🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨Deployment operation progress: C:\Users\Esco\AppData\Local\… [Completed
🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨  [N] Nont operation progress: Mozilla.MozillaFirefoxNightly… [Processing
Deployment operation progress: C:\Users\Esco\AppData\Local\… [Completed🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨 ]
Deployment operation progress: Mozilla.MozillaFirefoxNightly… [Completed🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨 ]
Deployment operation progress: C:\Users\Esco\AppData\Local\… [Completed🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨 ]
Deployment operation progress: Mozilla.MozillaFirefoxNightly… [Completed🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨 ]
Deployment operation progress: C:\Users\Esco\AppData\Local\… [Completed


🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨
🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨Deployment operation progress: Mozilla.MozillaFirefoxNightly… [Completed
🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨Deployment operation progress: C:\Users\Esco\AppData\Local\… [Completed
🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨Deployment operation progress: Mozilla.MozillaFirefoxNightly… [Processing
Deployment operation progress: C:\Users\Esco\AppData\Local\… [Completed🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨 ]
Deployment operation progress: Mozilla.MozillaFirefoxNightly… [Completed🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨 ]
Deployment operation progress: C:\Users\Esco\AppData\Local\… [Completed🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨 ]
Deployment operation progress: Mozilla.MozillaFirefoxNightly… [Completed🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨 ]
Deployment operation progress: C:\Users\Esco\AppData\Local\… [Completed


🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨
🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨Deployment operation progress: Mozilla.MozillaFirefoxNightly… [Completed
🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨Deployment operation progress: C:\Users\Esco\AppData\Local\… [Completed
🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨Enter Choice (default is 'Y'): Mozilla.MozillaFirefoxNightly… [Processing
Deployment operation progress: C:\Users\Esco\AppData\Local\… [Completed🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨 ]
Deployment operation progress: Mozilla.MozillaFirefoxNightly… [Completed🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨 ]
Deployment operation progress: C:\Users\Esco\AppData\Local\… [Completed🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨 ]
Deployment operation progress: Mozilla.MozillaFirefoxNightly… [Completed🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨🟨 ]
Deployment operation progress: C:\Users\Esco\AppData\Local\… [Completed




🟨🟨]
Deployment operation progress: Mozilla.MozillaFirefoxNightly… [Completed
🟨🟨]
Deployment operation progress: C:\Users\Esco\AppData\Local\… [Completed
🟨🟨]
Deployment operation progress: Mozilla.MozillaFirefoxNightly… [Processing
🟨🟨]
```

### Environment

```shell
Its been a issue for a looong time since we added the MSIX stuff

❯ $host

Name             : ConsoleHost
Version          : 7.2.1
InstanceId       : c9c31913-a267-48bc-9f0d-b25cae997779
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-150
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

**Comment by Trenly** [comment] 2022-02-18 15:39
I don't see any deployment progress on my side; Do you have something that could be overriding the `$ProgressPreference = 'SilentlyContinue'` of the script?
![image](https://user-images.githubusercontent.com/12611259/154713872-6e1afa77-6468-4f64-ac30-7ebe1ee15e21.png)

**Comment by OfficialEsco** [comment] 2022-02-18 15:52
Interesting, nope i don't change those variables

PS7
```
❯ git checkout origin/master -q && .\Tools\YamlCreate.ps1 -AutoUpgrade -PackageIdentifier Mozilla.Firefox.Nightly -PackageVersion 96.0a1 -SkipPRCheck

Found Existing Version: 96.0a1

Updating Manifest Information. This may take a while...
Reading Installer Database. This may take some time. . .
Closing Installer Database. . .
Reading Installer Database. This may take some time. . .
Closing Installer Database. . .
Reading Installer Database. This may take some time. . .
Closing Installer Database. . .
Reading Installer Database. This may take some time. . .
Closing Installer Database. . .

Yaml file created: C:\Users\Esco\GitHub\winget-pkgs\manifests\m\Mozilla\Firefox\Nightly\96.0a1\Mozilla.Firefox.Nightly.locale.en-US.yaml

Yaml file created: C:\Users\Esco\GitHub\winget-pkgs\manifests\m\Mozilla\Firefox\Nightly\96.0a1\Mozilla.Firefox.Nightly.installer.yaml

Yaml file created: C:\Users\Esco\GitHub\winget-pkgs\manifests\m\Mozilla\Firefox\Nightly\96.0a1\Mozilla.Firefox.Nightly.yaml


Do you want to submit your PR now?
  [Y] Yes
  [N] No

Enter Choice (default is 'Y'):
Deployment operation progress: C:\Users\Esco\AppData\Local\… [Processing                                            ]
Deployment operation progress: Mozilla.MozillaFirefoxNightly… [Processing                                            ]
Deployment operation progress: C:\Users\Esco\AppData\Local\… [Completed                                             ]
Deployment operation progress: Mozilla.MozillaFirefoxNightly… [Processing                                            ]
```

It appears to be a issue with PS7 cuz PS5 is clean

```
❯ git checkout origin/master -q | .\Tools\YamlCreate.ps1 -AutoUpgrade -PackageIdentifier Mozilla.Firefox.Nightly -PackageVersion 96.0a1 -SkipPRCheck

Found Existing Version: 96.0a1

Updating Manifest Information. This may take a while...
Reading Installer Database. This may take some time. . .
Closing Installer Database. . .
Reading Installer Database. This may take some time. . .
Closing Installer Database. . .
Reading Installer Database. This may take some time. . .
Closing Installer Database. . .
Reading Installer Database. This may take some time. . .
Closing Installer Database. . .

Yaml file created: C:\Users\Esco\GitHub\winget-pkgs\manifests\m\Mozilla\Firefox\Nightly\96.0a1\Mozilla.Firefox.Nightly.locale.en-US.yaml

Yaml file created: C:\Users\Esco\GitHub\winget-pkgs\manifests\m\Mozilla\Firefox\Nightly\96.0a1\Mozilla.Firefox.Nightly.installer.yaml

Yaml file created: C:\Users\Esco\GitHub\winget-pkgs\manifests\m\Mozilla\Firefox\Nightly\96.0a1\Mozilla.Firefox.Nightly.yaml
Manifest validation succeeded.


Do you want to submit your PR now?
  [Y] Yes
  [N] No

Enter Choice (default is 'Y'):
```

**Comment by OfficialEsco** [comment] 2022-02-18 16:07
Hold up, my `ProgressPreference` is actually `Continue`, is the default `SilentlyContinue`?

**Comment by OfficialEsco** [comment] 2022-02-18 16:18
No difference >:c

**Comment by OfficialEsco** [comment] 2022-02-18 17:10
Still `Continue` on both Powershell versions

**Comment by vedantmgoyal2009** [comment] 2022-02-18 17:18
Can you dotsource (`. .\Tools\YamlCreate.ps1`) and then check what `$ProgressPreference` is set to?

**Comment by OfficialEsco** [comment] 2022-02-18 17:28
I put `Write-Host "$ProgressPreference"` above every Add-AppxPackage and its actually set to SilentlyContinue 🤷‍♂️
```
PowerShell 7.2.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\User> C:\Users\User\Documents\winget-pkgs\Tools\YamlCreate.ps1 -AutoUpgrade -PackageIdentifier Mozilla.Firefox.Nightly -PackageVersion 96.0a1 -SkipPRCheck
SilentlyContinue

Found Existing Version: 96.0a1

Updating Manifest Information. This may take a while...
SilentlyContinue
Deployment operation progress: C:\Users\User\AppData\Local\T. [Processing                                            ]
Deployment operation progress: Mozilla.MozillaFirefoxNightly. [Processing                                            ]
```

**Comment by Trenly** [comment] 2022-02-18 17:32
Hmm. Can you try this to see if it's an issue with Add-AppxPackage or if it's with the progress setting in general?
You should only see one progress bar, if the preference starts as continue
```powershell
$max = 100000
Write-Output "Current Progress Preference: $ProgressPreference"
Write-Output "Initializing Progress Test"
(1..$max) | % {Write-Progress -Activity 'Testing Progress Bar. . .' -PercentComplete ($_*100/$max) -Status 'Progress bar should be visible'}
Write-Output 'Progress Test Complete'
Write-Output "Setting new progress preference"
$ProgressPreference = 'SilentlyContinue'
Write-Output "New Progress Preference: $ProgressPreference"
Write-Output "Initializing Progress Test"
(1..$max) | % {Write-Progress -Activity 'Testing Progress Bar. . .' -PercentComplete ($_*100/$max) -Status 'Progress bar should be hidden'}
Write-Output 'Progress Test Complete'
Write-Output 'Press any key to exit. . .'
$null = $Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown');
```

**Comment by Trenly** [comment] 2022-02-18 17:49
I think we need to get the PS7 team to help us here, since I don't know why the progress preference isn't being respected on your machine or your vm, when on my machine, sandbox, and Vedant's machine we don't see the progress bars at all

**Comment by Trenly** [comment] 2023-12-04 20:06
@OfficialEsco - I think I found the root cause of this while implementing #180 - take a look at https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/77#issuecomment-601947496

Either way, this should be resolved once https://github.com/microsoft/winget-pkgs/pull/129186 gets merged in

**Closed** 2023-12-06 13:52 UTC
Labels: Bug
